# Time durations (seconds)
MODEL_BAN_DURATION = 3600.0
DEFAULT_RETRY_DELAY = 2.0
DEFAULT_POLL_INTERVAL = 2.0
TRANSIENT_RETRY_LIMIT = 2
UNSAFE_IP_COOLDOWN = 21600.0  # 6 hours
TIMEOUT_IP_COOLDOWN = 3600.0  # 1 hour

# Chunking
STREAM_CHUNK_SIZE = 4

# Cache TTL
DEFAULT_MODEL_CACHE_TTL = 60

# Retry defaults
DEFAULT_MAX_RETRIES = 2
DEFAULT_BACKOFF_BASE = 2.0
DEFAULT_RATE_LIMIT_BACKOFF = 5.0

# Streaming
DEFAULT_STREAM_STALL_TIMEOUT = 120
